name: Deploy Next.js site to Pages

on:
  push:
    branches: ["main"]

  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
  
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
        # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
  
      # install node.js
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
  
      # Runs a single command using the runners shell
      - name: install dependencies
        run: npm install --force
  
      # Runs a single command using the runners shell
      - name: try to build the project
        run: npm run build && npm run export && touch ./out/.nojekyll
  
        # use actions-gh-pages to deploy dist to gh-pages
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          # github will auto-generate a token for this job and use it 
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./out
          cname: 'charlie26701.dev'  